import api from "@/lib/axios";

export interface WhatsappConfiguration {
    id: number;
    user_id: number;
    name: string;
    account_id: string;
    api_secret?: string;
    daily_limit: number;
    daily_usage: number;
    is_active: boolean;
    created_at?: string;
    updated_at?: string;
}

export const WhatsappService = {
    getConfigurations: async (): Promise<WhatsappConfiguration[]> => {
        const response = await api.get("/whatsapp-configurations");
        return response.data;
    },

    getConfiguration: async (id: number): Promise<WhatsappConfiguration> => {
        const response = await api.get(`/whatsapp-configurations/${id}`);
        return response.data;
    },

    createConfiguration: async (data: Partial<WhatsappConfiguration>): Promise<WhatsappConfiguration> => {
        const response = await api.post("/whatsapp-configurations", data);
        return response.data;
    },

    updateConfiguration: async (id: number, data: Partial<WhatsappConfiguration>): Promise<WhatsappConfiguration> => {
        const response = await api.put(`/whatsapp-configurations/${id}`, data);
        return response.data;
    },

    deleteConfiguration: async (id: number): Promise<void> => {
        await api.delete(`/whatsapp-configurations/${id}`);
    },

    sendTestWhatsapp: async (id: number, recipient: string, message: string): Promise<any> => {
        const response = await api.post(`/whatsapp-configurations/${id}/send-test-whatsapp`, {
            recipient,
            message
        });
        return response.data;
    },

    sendInvoiceNotification: async (config_id: number, recipient: string, invoiceDetails: {
        sales_code: string;
        customer_name: string;
        grand_total: number;
        paid_amount: number;
        sales_date: string;
        company_name: string;
    }): Promise<any> => {
        const balance = invoiceDetails.grand_total - invoiceDetails.paid_amount;
        const message =
            `📋 *Invoice Notification*\n\n` +
            `Hello *${invoiceDetails.customer_name}*,\n\n` +
            `Your invoice has been generated by *${invoiceDetails.company_name}*.\n\n` +
            `📌 *Invoice:* ${invoiceDetails.sales_code}\n` +
            `📅 *Date:* ${invoiceDetails.sales_date}\n` +
            `💰 *Total:* $${Number(invoiceDetails.grand_total).toFixed(2)}\n` +
            `✅ *Paid:* $${Number(invoiceDetails.paid_amount).toFixed(2)}\n` +
            `⚠️ *Balance Due:* $${Number(balance).toFixed(2)}\n\n` +
            `Thank you for your business!`;

        const response = await api.post(`/whatsapp-configurations/${config_id}/send-test-whatsapp`, {
            recipient,
            message
        });
        return response.data;
    }
};
