"use client";

import { useState, useEffect, useMemo } from "react";
import { useRouter } from "next/navigation";
import { useAuthStore } from "@/lib/store";
import { SaleService, SaleItem } from "@/lib/sales-purchase-service";
import { WarehouseService, type Warehouse } from "@/lib/warehouse-service";
import { ContactService } from "@/lib/contact-service";
import { ProductService } from "@/lib/product-service";
import { TaxService } from "@/lib/tax-bank-service";
import { AccountService } from "@/lib/accounting-import-service";
import { WhatsappService } from "@/lib/whatsapp-service";
import { EmailService } from "@/lib/email-service";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/components/ui/select";
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from "@/components/ui/table";
import {
    Plus,
    Trash2,
    Search,
    UserPlus,
    Calendar,
    ArrowLeft,
    Save,
    QrCode,
    Receipt,
    ShoppingCart,
    Minus,
    MessageCircle,
    Mail,
    FileText,
    CheckCircle2,
    Clock,
    AlertCircle,
    Wallet,
    ShieldCheck,
    MessageSquare,
    Calculator,
    Warehouse as WarehouseIcon,
    Users
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { useTranslation } from "@/i18n/TranslationContext";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";

export default function NewSalePage() {
    const router = useRouter();
    const { t } = useTranslation();
    const { currentCompany } = useAuthStore();
    const [loading, setLoading] = useState(false);
    const [sendWhatsapp, setSendWhatsapp] = useState(true);
    const [whatsappConfig, setWhatsappConfig] = useState<any>(null);
    const [sendEmail, setSendEmail] = useState(true);
    const [emailConfig, setEmailConfig] = useState<any>(null);

    // Master Data
    const [warehouses, setWarehouses] = useState<Warehouse[]>([]);
    const [customers, setCustomers] = useState<any[]>([]);
    const [products, setProducts] = useState<any[]>([]);
    const [taxes, setTaxes] = useState<any[]>([]);
    const [accounts, setAccounts] = useState<any[]>([]);
    const [previousPayments, setPreviousPayments] = useState<any[]>([]);

    // Form State
    const [formData, setFormData] = useState({
        warehouse_id: "",
        customer_id: "",
        sales_code: "", // Will be auto-generated by backend
        sales_date: new Date().toISOString().split('T')[0],
        due_date: "",
        reference_no: "Manual",
        other_charges: 0,
        discount_on_all: 0,
        discount_type: 'Percentage' as 'Percentage' | 'Fixed',
        note: "",
        terms_and_conditions: "",
        status: 'Final' as 'Final' | 'Quotation' | 'Proforma',
        paid_amount: 0,
        payment_type: 'Cash',
        account_id: "",
        payment_note: "",
        payment_status: 'Unpaid' as 'Paid' | 'Partial' | 'Unpaid',
        use_advance: false
    });

    const [items, setItems] = useState<any[]>([]);
    const [searchQuery, setSearchQuery] = useState("");

    useEffect(() => {
        if (currentCompany) {
            WarehouseService.getAll(currentCompany.id).then(setWarehouses).catch(() => { });
            ContactService.getAll(currentCompany.id).then(data => setCustomers(data.filter(c => c.type === 'customer'))).catch(() => { });
            ProductService.getAll(currentCompany.id).then(setProducts).catch(() => { });
            TaxService.getAll(currentCompany.id).then(setTaxes).catch(() => { });
            AccountService.getAll(currentCompany.id).then(setAccounts).catch(() => { });
            WhatsappService.getConfigurations().then(configs => {
                const active = configs.find(c => c.is_active);
                if (active) setWhatsappConfig(active);
            }).catch(() => { });
            EmailService.getConfigurations().then(configs => {
                const active = configs.find(c => c.is_active);
                if (active) setEmailConfig(active);
            }).catch(() => { });
        }
    }, [currentCompany]);

    useEffect(() => {
        if (warehouses.length > 0 && !formData.warehouse_id) {
            const mainWH = warehouses.find(w => w.name.toLowerCase().includes('main'));
            setFormData(prev => ({ ...prev, warehouse_id: (mainWH?.id || warehouses[0].id).toString() }));
        }
    }, [warehouses]);

    useEffect(() => {
        if (accounts.length > 0 && !formData.account_id) {
            const cashAcc = accounts.find(a => a.name.toUpperCase() === 'CASH');
            if (cashAcc) {
                setFormData(prev => ({ ...prev, account_id: cashAcc.id.toString() }));
            }
        }
    }, [accounts]);

    const selectedCustomer = useMemo(() => {
        return customers.find(c => c.id.toString() === formData.customer_id);
    }, [customers, formData.customer_id]);

    // Calculations
    const totals = useMemo(() => {
        const subtotal = items.reduce((acc, item) => acc + (item.quantity * item.unit_price), 0);
        const itemDiscount = items.reduce((acc, item) => acc + (item.discount_amount || 0), 0);
        const taxAmount = items.reduce((acc, item) => acc + (item.tax_amount || 0), 0);

        let globalDiscount = 0;
        if (formData.discount_type === 'Percentage') {
            globalDiscount = subtotal * (formData.discount_on_all / 100);
        } else {
            globalDiscount = formData.discount_on_all;
        }

        const grandTotal = subtotal + Number(formData.other_charges) - globalDiscount + taxAmount;
        const currentBalance = grandTotal - Number(formData.paid_amount);
        const totalDue = currentBalance + (selectedCustomer?.previous_due || 0);

        // Calculate payment status
        let paymentStatus: 'PAID' | 'PARTIAL' | 'UNPAID' = 'UNPAID';
        if (formData.paid_amount > 0) {
            if (formData.paid_amount >= grandTotal) {
                paymentStatus = 'PAID';
            } else {
                paymentStatus = 'PARTIAL';
            }
        }

        return {
            subtotal,
            itemDiscount,
            taxAmount,
            globalDiscount,
            grandTotal,
            balance: totalDue,
            paymentStatus,
            quantity: items.reduce((acc, item) => acc + Number(item.quantity), 0)
        };
    }, [items, formData.other_charges, formData.discount_on_all, formData.discount_type, formData.paid_amount, selectedCustomer]);

    const getDynamicFontSize = (text: string, type: 'grandTotal' | 'paidAmount' | 'balanceDue') => {
        const length = text.length;
        if (type === 'grandTotal') {
            if (length > 18) return 'text-base md:text-lg lg:text-xl';
            if (length > 15) return 'text-lg md:text-xl lg:text-2xl';
            return 'text-xl md:text-2xl lg:text-3xl';
        }
        if (type === 'paidAmount') {
            if (length > 15) return 'text-xs md:text-sm';
            return 'text-sm md:text-base lg:text-lg';
        }
        if (type === 'balanceDue') {
            if (length > 15) return 'text-[10px] md:text-xs';
            return 'text-xs md:text-sm';
        }
        return '';
    };

    const addItem = (product: any) => {
        if (!formData.warehouse_id || !formData.customer_id) {
            toast.warning(t("sales.select_warehouse_customer_warning") || "Please select warehouse and customer first.");
            return;
        }
        if (product.stock_quantity <= 0) {
            toast.error(t("sales.out_of_stock") || "Product is out of stock!");
            return;
        }
        const existing = items.find(i => i.product_id === product.id);
        if (existing) {
            setItems(items.map(i => i.product_id === product.id
                ? { ...i, quantity: i.quantity + 1, total_amount: (i.quantity + 1) * i.unit_price }
                : i
            ));
        } else {
            setItems([...items, {
                product_id: product.id,
                name: product.name,
                quantity: 1,
                unit_price: product.sales_price,
                discount_amount: 0,
                tax_id: product.tax_id,
                tax_amount: 0, // Simplified for now
                total_amount: product.sales_price
            }]);
        }
        setSearchQuery("");
    };

    const updateItem = (index: number, field: string, value: any) => {
        const newItems = [...items];
        newItems[index] = { ...newItems[index], [field]: value };

        // Recalculate total_amount for the item
        if (field === 'quantity' || field === 'unit_price') {
            newItems[index].total_amount = newItems[index].quantity * newItems[index].unit_price;
        }

        setItems(newItems);
    };

    const removeItem = (index: number) => {
        setItems(items.filter((_, i) => i !== index));
    };

    const handleSubmit = async (isDraft: boolean) => {
        if (!formData.warehouse_id || !formData.customer_id) {
            toast.error(t("common.warning"));
            return;
        }
        if (items.length === 0) {
            toast.error(t("sales.empty_items"));
            return;
        }
        setLoading(true);
        try {
            const saleResult = await SaleService.create({
                ...formData,
                company_id: currentCompany?.id || 0,
                warehouse_id: Number(formData.warehouse_id),
                customer_id: Number(formData.customer_id),
                subtotal: totals.subtotal,
                grand_total: totals.grandTotal,
                items: items,
                status: isDraft ? 'Quotation' : 'Final',
                account_id: formData.account_id ? Number(formData.account_id) : undefined,
            });
            
            toast.success(t("common.created_successfully"));

            // Notification Logic (Simplified)
            if (sendWhatsapp && whatsappConfig && selectedCustomer?.mobile) {
                WhatsappService.sendInvoiceNotification(whatsappConfig.id, selectedCustomer.mobile, {
                    sales_code: saleResult?.sales_code || 'N/A',
                    customer_name: selectedCustomer.name,
                    grand_total: totals.grandTotal,
                    paid_amount: formData.paid_amount,
                    sales_date: formData.sales_date,
                    company_name: currentCompany?.name || "",
                }).catch(() => { });
            }

            router.push("/sales");
        } catch (error: any) {
            toast.error(t("common.error_occurred"));
        } finally {
            setLoading(false);
        }
    };

    const filteredProducts = useMemo(() => {
        if (!searchQuery) return [];
        return products.filter(p => 
            p.name.toLowerCase().includes(searchQuery.toLowerCase()) || 
            p.sku?.toLowerCase().includes(searchQuery.toLowerCase())
        ).slice(0, 5);
    }, [products, searchQuery]);

    return (
        <div className="w-full p-4 md:p-6 space-y-6 pb-20">
            {/* Header */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-6">
                <div className="flex items-center gap-3">
                    <Button variant="ghost" size="icon" onClick={() => router.back()} className="rounded-xl">
                        <ArrowLeft size={20} />
                    </Button>
                    <div className="flex flex-col gap-1">
                        <h1 className="text-2xl md:text-3xl font-black bg-gradient-to-r from-orange-400 via-indigo-600 to-purple-600 bg-clip-text text-transparent tracking-tighter uppercase leading-tight pt-[5px]">
                            {t("sales.create_title")}
                        </h1>
                        <p className="text-[9px] md:text-[11px] text-zinc-500 dark:text-zinc-400 font-black tracking-[0.2em] uppercase opacity-70">
                            {t("sales.create_subtitle")}
                        </p>
                    </div>
                </div>
                <div className="flex items-center gap-3">
                    <Button variant="outline" onClick={() => handleSubmit(true)} disabled={loading} className="rounded-xl">
                        <FileText className="w-4 h-4 mr-2 text-slate-500" />
                        {t("sales.draft")}
                    </Button>
                    <Button onClick={() => handleSubmit(false)} disabled={loading} className="bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl shadow-lg shadow-indigo-200 dark:shadow-none">
                        <Save className="w-4 h-4 mr-2" />
                        {t("sales.save_invoice")}
                    </Button>
                </div>
            </div>

            <form className="grid grid-cols-1 xl:grid-cols-4 gap-6">
                {/* Main Form Area */}
                <div className="xl:col-span-3 space-y-6">
                    <Card className="border-0 shadow-2xl shadow-indigo-500/5 rounded-xl overflow-hidden">
                        <CardContent className="p-8">
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                                <div className="space-y-3">
                                    <div className="flex items-center gap-2 mb-2">
                                        <div className="p-1.5 rounded-md bg-indigo-50 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400">
                                            <WarehouseIcon className="w-4 h-4" />
                                        </div>
                                        <Label className="text-sm font-semibold">{t("sales.warehouse")}</Label>
                                    </div>
                                    <Select
                                        value={formData.warehouse_id}
                                        onValueChange={(val) => setFormData({ ...formData, warehouse_id: val })}
                                    >
                                        <SelectTrigger className="bg-white dark:bg-slate-950 border-slate-200 dark:border-slate-800 focus:ring-indigo-500 rounded-xl h-12">
                                            <SelectValue placeholder={t("sales.select_warehouse")} />
                                        </SelectTrigger>
                                        <SelectContent className="rounded-xl">
                                            {warehouses.map(w => (
                                                <SelectItem key={w.id} value={w.id.toString()}>{w.name}</SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                </div>

                                <div className="space-y-3">
                                    <div className="flex items-center justify-between mb-2">
                                        <div className="flex items-center gap-2">
                                            <div className="p-1.5 rounded-md bg-amber-50 dark:bg-amber-900/30 text-amber-600 dark:text-amber-400">
                                                <Users className="w-4 h-4" />
                                            </div>
                                            <Label className="text-sm font-semibold">{t("sales.customer_name")}</Label>
                                        </div>
                                        {selectedCustomer?.outstanding_balance > 0 && (
                                            <Badge variant="outline" className="text-[10px] bg-red-50 text-red-600 border-red-100">
                                                {t("sales.previous_due") || "Previous Due"}: {currentCompany?.currency} {selectedCustomer.outstanding_balance.toLocaleString()}
                                            </Badge>
                                        )}
                                    </div>
                                    <div className="flex gap-2">
                                        <Select
                                            value={formData.customer_id}
                                            onValueChange={(val) => setFormData({ ...formData, customer_id: val })}
                                        >
                                            <SelectTrigger className="bg-white dark:bg-slate-950 border-slate-200 dark:border-slate-800 focus:ring-indigo-500 rounded-xl h-12 flex-1">
                                                <SelectValue placeholder={t("sales.select_customer")} />
                                            </SelectTrigger>
                                            <SelectContent className="rounded-xl">
                                                {customers.map(c => (
                                                    <SelectItem key={c.id} value={c.id.toString()}>{c.name}</SelectItem>
                                                ))}
                                            </SelectContent>
                                        </Select>
                                        <Button type="button" variant="outline" size="icon" className="h-12 w-12 rounded-xl border-slate-200 dark:border-slate-800">
                                            <UserPlus size={18} className="text-indigo-600" />
                                        </Button>
                                    </div>
                                </div>

                                <div className="space-y-3">
                                    <div className="flex items-center gap-2 mb-2">
                                        <div className="p-1.5 rounded-md bg-emerald-50 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-400">
                                            <Calendar className="w-4 h-4" />
                                        </div>
                                        <Label className="text-sm font-semibold">{t("sales.sales_date")}</Label>
                                    </div>
                                    <Input
                                        type="date"
                                        value={formData.sales_date}
                                        onChange={(e) => setFormData({ ...formData, sales_date: e.target.value })}
                                        className="h-12 bg-white dark:bg-slate-950 border-slate-200 dark:border-slate-800 rounded-xl focus:ring-indigo-500 font-bold"
                                    />
                                </div>
                            </div>
                        </CardContent>
                    </Card>

                    {/* Item Search & Table */}
                    <Card className="border-0 shadow-2xl shadow-indigo-500/5 rounded-xl overflow-hidden">
                        <CardContent className="p-0">
                            <div className="p-8 pb-4">
                                <div className="relative group">
                                    <Input
                                        placeholder={t("sales.item_search_placeholder")}
                                        value={searchQuery}
                                        onChange={(e) => setSearchQuery(e.target.value)}
                                        className="h-14 pl-14 pr-14 bg-white dark:bg-slate-950 border-slate-200 dark:border-slate-800 rounded-xl focus:ring-2 focus:ring-indigo-500/20 text-lg font-bold"
                                    />
                                    <Search className="absolute left-6 top-1/2 -translate-y-1/2 text-slate-400 group-focus-within:text-indigo-500 transition-colors" size={22} />
                                    <QrCode className="absolute right-6 top-1/2 -translate-y-1/2 text-slate-400 cursor-pointer hover:text-indigo-500 transition-colors" size={22} />

                                    {/* Search Results Dropdown */}
                                    {filteredProducts.length > 0 && (
                                        <div className="absolute top-full left-0 right-0 mt-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-2xl z-50 p-2 overflow-hidden">
                                            {filteredProducts.map(p => (
                                                <div
                                                    key={p.id}
                                                    onClick={() => addItem(p)}
                                                    className="flex items-center justify-between p-4 cursor-pointer hover:bg-slate-50 dark:hover:bg-slate-800 rounded-xl transition-all group"
                                                >
                                                    <div className="flex items-center gap-4">
                                                        <div className="h-10 w-10 rounded-lg bg-indigo-50 dark:bg-indigo-900/30 flex items-center justify-center font-bold text-indigo-600">
                                                            {p.name[0]}
                                                        </div>
                                                        <div>
                                                            <div className="font-bold text-slate-900 dark:text-slate-100">{p.name}</div>
                                                            <div className="text-[10px] text-slate-500 uppercase tracking-widest">{p.sku}</div>
                                                        </div>
                                                    </div>
                                                    <div className="text-right">
                                                        <div className="font-black text-indigo-600">{currentCompany?.currency} {p.sales_price}</div>
                                                        <div className="text-[10px] text-slate-400 font-bold uppercase tracking-widest">{t("inventory.table_stock")}: {p.stock_quantity}</div>
                                                    </div>
                                                </div>
                                            ))}
                                        </div>
                                    )}
                                </div>
                            </div>

                            <div className="overflow-x-auto min-h-[300px]">
                                <Table>
                                    <TableHeader className="bg-slate-50/50 dark:bg-slate-900/50 border-b border-slate-200 dark:border-slate-800">
                                        <TableRow className="hover:bg-transparent">
                                            <TableHead className="pl-8 py-4 font-bold text-xs uppercase tracking-widest text-slate-500">{t("sales.table_item_name")}</TableHead>
                                            <TableHead className="py-4 font-bold text-xs uppercase tracking-widest text-slate-500 text-center">{t("sales.table_qty")}</TableHead>
                                            <TableHead className="py-4 font-bold text-xs uppercase tracking-widest text-slate-500 text-right">{t("sales.table_unit_price")}</TableHead>
                                            <TableHead className="py-4 font-bold text-xs uppercase tracking-widest text-slate-500 text-right">{t("sales.table_discount")}</TableHead>
                                            <TableHead className="py-4 font-bold text-xs uppercase tracking-widest text-slate-500 text-right">{t("sales.table_tax")}</TableHead>
                                            <TableHead className="pr-8 py-4 font-bold text-xs uppercase tracking-widest text-slate-500 text-right">{t("sales.table_total")}</TableHead>
                                            <TableHead className="w-16"></TableHead>
                                        </TableRow>
                                    </TableHeader>
                                    <TableBody>
                                        {items.map((item, idx) => (
                                            <TableRow key={idx} className="border-slate-100 dark:border-slate-800 hover:bg-slate-50/30 dark:hover:bg-slate-800/30 transition-colors group">
                                                <TableCell className="pl-8 py-6">
                                                    <div className="font-bold text-slate-900 dark:text-slate-100">{item.name}</div>
                                                </TableCell>
                                                <TableCell className="text-center">
                                                    <Input
                                                        type="number"
                                                        value={item.quantity}
                                                        onChange={(e) => updateItem(idx, 'quantity', Number(e.target.value))}
                                                        className="h-10 w-20 mx-auto bg-transparent border-slate-200 dark:border-slate-800 rounded-xl text-center font-bold"
                                                    />
                                                </TableCell>
                                                <TableCell className="text-right">
                                                    <Input
                                                        type="number"
                                                        value={item.unit_price}
                                                        onChange={(e) => updateItem(idx, 'unit_price', Number(e.target.value))}
                                                        className="h-10 w-28 ml-auto bg-transparent border-slate-200 dark:border-slate-800 rounded-xl text-right font-bold"
                                                    />
                                                </TableCell>
                                                <TableCell className="text-right font-medium text-slate-400">
                                                    {currentCompany?.currency} {item.discount_amount}
                                                </TableCell>
                                                <TableCell className="text-right font-medium text-slate-400">
                                                    {currentCompany?.currency} {item.tax_amount}
                                                </TableCell>
                                                <TableCell className="pr-8 text-right">
                                                    <div className="font-black text-indigo-600">{currentCompany?.currency} {Number(item.total_amount).toFixed(2)}</div>
                                                </TableCell>
                                                <TableCell className="pr-8 text-right">
                                                    <Button
                                                        type="button"
                                                        variant="ghost"
                                                        size="icon"
                                                        onClick={() => removeItem(idx)}
                                                        className="h-9 w-9 rounded-xl text-slate-300 hover:text-red-500 hover:bg-red-50"
                                                    >
                                                        <Trash2 size={16} />
                                                    </Button>
                                                </TableCell>
                                            </TableRow>
                                        ))}
                                        {items.length === 0 && (
                                            <TableRow>
                                                <TableCell colSpan={7} className="h-60 text-center">
                                                    <div className="flex flex-col items-center gap-3 text-slate-300 dark:text-slate-700">
                                                        <ShoppingCart size={48} className="opacity-20" />
                                                        <span className="font-bold uppercase tracking-widest text-xs">{t("sales.empty_items")}</span>
                                                    </div>
                                                </TableCell>
                                            </TableRow>
                                        )}
                                    </TableBody>
                                </Table>
                            </div>
                        </CardContent>
                    </Card>

                    {/* Terms & Notification Area */}
                    <Card className="border-0 shadow-2xl shadow-indigo-500/5 rounded-xl p-8 space-y-6">
                        <div className="space-y-3">
                            <Label className="text-sm font-bold flex items-center gap-2">
                                <FileText className="w-4 h-4 text-slate-400" />
                                {t("sales.terms_title")}
                            </Label>
                            <Textarea
                                placeholder={t("sales.terms_placeholder")}
                                className="min-h-[120px] rounded-xl border-slate-200 dark:border-slate-800 p-4 focus:ring-indigo-500/20"
                                value={formData.terms_and_conditions}
                                onChange={(e) => setFormData({ ...formData, terms_and_conditions: e.target.value })}
                            />
                        </div>

                        <div className="flex flex-wrap gap-6 pt-4 border-t border-slate-100 dark:border-slate-800">
                            <div className="flex items-center gap-3 bg-slate-50 dark:bg-slate-900 px-4 py-3 rounded-xl border border-slate-100 dark:border-slate-800">
                                <Switch id="ws-notif" checked={sendWhatsapp} onCheckedChange={setSendWhatsapp} />
                                <Label htmlFor="ws-notif" className="text-sm font-bold flex items-center gap-2 cursor-pointer">
                                    <MessageSquare size={16} className="text-green-500" /> {t("sales.whatsapp_notif")}
                                </Label>
                            </div>
                            <div className="flex items-center gap-3 bg-slate-50 dark:bg-slate-900 px-4 py-3 rounded-xl border border-slate-100 dark:border-slate-800">
                                <Switch id="email-notif" checked={sendEmail} onCheckedChange={setSendEmail} />
                                <Label htmlFor="email-notif" className="text-sm font-bold flex items-center gap-2 cursor-pointer">
                                    <Mail size={16} className="text-indigo-500" /> {t("sales.email_notif")}
                                </Label>
                            </div>
                        </div>
                    </Card>
                </div>

                {/* Sidebar Sticky Panel */}
                <div className="space-y-6">
                    <Card className="border-0 bg-indigo-600 dark:bg-indigo-700 shadow-2xl shadow-indigo-500/20 rounded-xl overflow-hidden sticky top-24">
                        <CardContent className="p-8 space-y-8 text-white">
                            <div className="space-y-2">
                                <p className="text-[10px] font-black uppercase tracking-widest text-indigo-100/60">{t("sales.grand_total")}</p>
                                <h3 className={cn(
                                    "font-black tracking-tighter transition-all",
                                    getDynamicFontSize(`${currentCompany?.currency} ${Number(totals.grandTotal).toLocaleString()}`, 'grandTotal')
                                )}>{currentCompany?.currency} {Number(totals.grandTotal).toLocaleString()}</h3>
                            </div>

                            <div className="space-y-6 pt-6 border-t border-white/10">
                                <div className="space-y-3">
                                    <Label className="text-[10px] font-black uppercase tracking-widest text-indigo-100/60">{t("sales.discount_on_all")}</Label>
                                    <div className="flex gap-2">
                                        <Input
                                            type="number"
                                            className="h-11 bg-white/10 border-white/10 rounded-xl focus:ring-white/20 text-white font-bold"
                                            value={formData.discount_on_all}
                                            onChange={(e) => setFormData({ ...formData, discount_on_all: parseFloat(e.target.value) || 0 })}
                                        />
                                        <Select
                                            value={formData.discount_type}
                                            onValueChange={(val: any) => setFormData({ ...formData, discount_type: val })}
                                        >
                                            <SelectTrigger className="h-11 w-20 bg-white/10 border-white/10 rounded-xl text-white font-bold">
                                                <SelectValue />
                                            </SelectTrigger>
                                            <SelectContent className="rounded-xl">
                                                <SelectItem value="Percentage">%</SelectItem>
                                                <SelectItem value="Fixed">{currentCompany?.currency}</SelectItem>
                                            </SelectContent>
                                        </Select>
                                    </div>
                                </div>

                                <div className="space-y-3">
                                    <Label className="text-[10px] font-black uppercase tracking-widest text-indigo-100/60">{t("sales.paid_amount")}</Label>
                                    <div className="relative">
                                        <div className="absolute left-3 top-1/2 -translate-y-1/2 text-white/40 font-bold">{currentCompany?.currency}</div>
                                        <Input
                                            type="number"
                                            className="h-11 pl-12 bg-white/10 border-white/10 rounded-xl focus:ring-white/20 text-white font-bold text-right"
                                            value={formData.paid_amount}
                                            onChange={(e) => setFormData({ ...formData, paid_amount: parseFloat(e.target.value) || 0 })}
                                        />
                                    </div>
                                </div>

                                <div className="space-y-1">
                                    <p className="text-[10px] font-black uppercase tracking-widest text-indigo-100/60">{t("sales.balance_due")}</p>
                                    <h4 className="font-black text-xl text-white">{currentCompany?.currency} {Number(totals.balance).toLocaleString()}</h4>
                                </div>
                            </div>
                        </CardContent>
                    </Card>

                    <Card className="border-0 shadow-xl rounded-xl p-8 space-y-4">
                        <div className="flex justify-between text-xs font-bold text-slate-500 uppercase tracking-widest">
                            <span>{t("sales.table_qty")}</span>
                            <span className="text-slate-900 dark:text-slate-100">{totals.quantity}</span>
                        </div>
                        <div className="flex justify-between text-xs font-bold text-slate-500 uppercase tracking-widest">
                            <span>{t("common.subtotal")}</span>
                            <span className="text-slate-900 dark:text-slate-100">{currentCompany?.currency} {Number(totals.subtotal).toLocaleString()}</span>
                        </div>
                        <div className="flex justify-between text-xs font-bold text-slate-500 uppercase tracking-widest">
                            <span>{t("sales.table_tax")}</span>
                            <span className="text-slate-900 dark:text-slate-100 text-indigo-600">{currentCompany?.currency} {Number(totals.taxAmount).toLocaleString()}</span>
                        </div>
                        <div className="pt-4 border-t border-slate-100 dark:border-slate-800 flex justify-between items-center">
                            <span className="text-[10px] font-black uppercase tracking-widest text-indigo-600">{t("sales.total_payable") || "Total Payable"}</span>
                            <span className="text-xl font-black text-indigo-600">{currentCompany?.currency} {Number(totals.grandTotal).toLocaleString()}</span>
                        </div>
                    </Card>

                    <div className="grid grid-cols-2 gap-3">
                        <Button onClick={() => handleSubmit(false)} disabled={loading} className="h-14 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl font-black uppercase tracking-widest shadow-xl shadow-indigo-500/20 border-0">
                            <Save className="mr-2 w-5 h-5" />
                            {t("sales.save")}
                        </Button>
                        <Button variant="outline" onClick={() => router.push('/sales')} className="h-14 rounded-xl font-black uppercase tracking-widest border-slate-200 dark:border-slate-800 text-slate-500">
                            {t("sales.close")}
                        </Button>
                    </div>
                </div>
            </form>
        </div>
    );
}
