"use client";

import { useState, useEffect, useMemo } from "react";
import { useRouter } from "next/navigation";
import { useAuthStore } from "@/lib/store";
import { SaleService, SaleItem } from "@/lib/sales-purchase-service";
import { WarehouseService, Warehouse } from "@/lib/warehouse-service";
import { ContactService } from "@/lib/contact-service";
import { ProductService } from "@/lib/product-service";
import { TaxService } from "@/lib/tax-bank-service";
import { AccountService } from "@/lib/accounting-import-service";
import { WhatsappService } from "@/lib/whatsapp-service";
import { EmailService } from "@/lib/email-service";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/components/ui/select";
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from "@/components/ui/table";
import {
    Plus,
    Trash2,
    Search,
    UserPlus,
    Calendar,
    ArrowLeft,
    Save,
    QrCode,
    Receipt,
    ShoppingCart,
    Minus,
    MessageCircle,
    Mail
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { toast } from "sonner";
import { cn } from "@/lib/utils";

export default function NewSalePage() {
    const router = useRouter();
    const { currentCompany } = useAuthStore();
    const [loading, setLoading] = useState(false);
    const [sendWhatsapp, setSendWhatsapp] = useState(true);
    const [whatsappConfig, setWhatsappConfig] = useState<any>(null);
    const [sendEmail, setSendEmail] = useState(true);
    const [emailConfig, setEmailConfig] = useState<any>(null);

    // Master Data
    const [warehouses, setWarehouses] = useState<Warehouse[]>([]);
    const [customers, setCustomers] = useState<any[]>([]);
    const [products, setProducts] = useState<any[]>([]);
    const [taxes, setTaxes] = useState<any[]>([]);
    const [accounts, setAccounts] = useState<any[]>([]);
    const [previousPayments, setPreviousPayments] = useState<any[]>([]);

    // Form State
    const [formData, setFormData] = useState({
        warehouse_id: "",
        customer_id: "",
        sales_code: "", // Will be auto-generated by backend
        sales_date: new Date().toISOString().split('T')[0],
        due_date: "",
        reference_no: "Manual",
        other_charges: 0,
        discount_on_all: 0,
        discount_type: 'Percentage' as 'Percentage' | 'Fixed',
        note: "",
        terms_and_conditions: "",
        status: 'Final' as 'Final' | 'Quotation' | 'Proforma',
        paid_amount: 0,
        payment_type: 'Cash',
        account_id: "",
        payment_note: "",
    });

    const [items, setItems] = useState<any[]>([]);
    const [searchQuery, setSearchQuery] = useState("");

    useEffect(() => {
        if (currentCompany) {
            WarehouseService.getAll(currentCompany.id).then(setWarehouses).catch(() => { });
            ContactService.getAll(currentCompany.id).then(data => setCustomers(data.filter(c => c.type === 'customer'))).catch(() => { });
            ProductService.getAll(currentCompany.id).then(setProducts).catch(() => { });
            TaxService.getAll(currentCompany.id).then(setTaxes).catch(() => { });
            AccountService.getAll(currentCompany.id).then(setAccounts).catch(() => { });
            WhatsappService.getConfigurations().then(configs => {
                const active = configs.find(c => c.is_active);
                if (active) setWhatsappConfig(active);
            }).catch(() => { });
            EmailService.getConfigurations().then(configs => {
                const active = configs.find(c => c.is_active);
                if (active) setEmailConfig(active);
            }).catch(() => { });
        }
    }, [currentCompany]);

    useEffect(() => {
        if (warehouses.length > 0 && !formData.warehouse_id) {
            const mainWH = warehouses.find(w => w.name.toLowerCase().includes('main'));
            setFormData(prev => ({ ...prev, warehouse_id: (mainWH?.id || warehouses[0].id).toString() }));
        }
    }, [warehouses]);

    useEffect(() => {
        if (accounts.length > 0 && !formData.account_id) {
            const cashAcc = accounts.find(a => a.name.toUpperCase() === 'CASH');
            if (cashAcc) {
                setFormData(prev => ({ ...prev, account_id: cashAcc.id.toString() }));
            }
        }
    }, [accounts]);

    const selectedCustomer = useMemo(() => {
        return customers.find(c => c.id.toString() === formData.customer_id);
    }, [customers, formData.customer_id]);

    // Calculations
    const totals = useMemo(() => {
        const subtotal = items.reduce((acc, item) => acc + (item.quantity * item.unit_price), 0);
        const itemDiscount = items.reduce((acc, item) => acc + (item.discount_amount || 0), 0);
        const taxAmount = items.reduce((acc, item) => acc + (item.tax_amount || 0), 0);

        let globalDiscount = 0;
        if (formData.discount_type === 'Percentage') {
            globalDiscount = subtotal * (formData.discount_on_all / 100);
        } else {
            globalDiscount = formData.discount_on_all;
        }

        const grandTotal = subtotal + Number(formData.other_charges) - globalDiscount + taxAmount;
        const currentBalance = grandTotal - Number(formData.paid_amount);
        const totalDue = currentBalance + (selectedCustomer?.previous_due || 0);

        // Calculate payment status
        let paymentStatus: 'PAID' | 'PARTIAL' | 'UNPAID' = 'UNPAID';
        if (formData.paid_amount > 0) {
            if (formData.paid_amount >= grandTotal) {
                paymentStatus = 'PAID';
            } else {
                paymentStatus = 'PARTIAL';
            }
        }

        return {
            subtotal,
            itemDiscount,
            taxAmount,
            globalDiscount,
            grandTotal,
            balance: totalDue,
            paymentStatus,
            quantity: items.reduce((acc, item) => acc + Number(item.quantity), 0)
        };
    }, [items, formData.other_charges, formData.discount_on_all, formData.discount_type, formData.paid_amount, selectedCustomer]);

    const getDynamicFontSize = (text: string, type: 'grandTotal' | 'paidAmount' | 'balanceDue') => {
        const length = text.length;
        if (type === 'grandTotal') {
            if (length > 18) return 'text-base md:text-lg lg:text-xl';
            if (length > 15) return 'text-lg md:text-xl lg:text-2xl';
            return 'text-xl md:text-2xl lg:text-3xl';
        }
        if (type === 'paidAmount') {
            if (length > 15) return 'text-xs md:text-sm';
            return 'text-sm md:text-base lg:text-lg';
        }
        if (type === 'balanceDue') {
            if (length > 15) return 'text-[10px] md:text-xs';
            return 'text-xs md:text-sm';
        }
        return '';
    };

    const addItem = (product: any) => {
        if (product.stock_quantity <= 0) {
            toast.error("Product is out of stock!");
            return;
        }
        const existing = items.find(i => i.product_id === product.id);
        if (existing) {
            setItems(items.map(i => i.product_id === product.id
                ? { ...i, quantity: i.quantity + 1, total_amount: (i.quantity + 1) * i.unit_price }
                : i
            ));
        } else {
            setItems([...items, {
                product_id: product.id,
                name: product.name,
                quantity: 1,
                unit_price: product.sales_price,
                discount_amount: 0,
                tax_id: product.tax_id,
                tax_amount: 0, // Simplified for now
                total_amount: product.sales_price
            }]);
        }
        setSearchQuery("");
    };

    const updateItem = (index: number, field: string, value: any) => {
        const newItems = [...items];
        newItems[index] = { ...newItems[index], [field]: value };

        // Recalculate total_amount for the item
        if (field === 'quantity' || field === 'unit_price') {
            newItems[index].total_amount = newItems[index].quantity * newItems[index].unit_price;
        }

        setItems(newItems);
    };

    const removeItem = (index: number) => {
        setItems(items.filter((_, i) => i !== index));
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!currentCompany) return;
        if (items.length === 0) {
            toast.error("Please add at least one item");
            return;
        }

        setLoading(true);
        try {
            const saleResult = await SaleService.create({
                ...formData,
                company_id: currentCompany.id,
                warehouse_id: Number(formData.warehouse_id),
                customer_id: Number(formData.customer_id),
                subtotal: totals.subtotal,
                grand_total: totals.grandTotal,
                items: items,
                terms_and_conditions: formData.terms_and_conditions,
                account_id: formData.account_id ? Number(formData.account_id) : undefined,
                payment_type: formData.payment_type,
                payment_note: formData.payment_note
            });
            toast.success("Invoice created successfully");

            // Send WhatsApp notification if enabled
            if (sendWhatsapp && whatsappConfig && selectedCustomer?.mobile) {
                try {
                    await WhatsappService.sendInvoiceNotification(whatsappConfig.id, selectedCustomer.mobile, {
                        sales_code: saleResult?.sales_code || formData.sales_code || 'N/A',
                        customer_name: selectedCustomer.name,
                        grand_total: totals.grandTotal,
                        paid_amount: formData.paid_amount,
                        sales_date: formData.sales_date,
                        company_name: currentCompany.name,
                    });
                    toast.success("WhatsApp notification sent!");
                } catch {
                    toast.warning("Invoice saved, but WhatsApp notification failed.");
                }
            }

            // Send Email notification if enabled
            if (sendEmail && emailConfig && selectedCustomer?.email) {
                try {
                    await EmailService.sendInvoiceEmail(emailConfig.id, selectedCustomer.email, {
                        sales_code: saleResult?.sales_code || formData.sales_code || 'N/A',
                        customer_name: selectedCustomer.name,
                        grand_total: totals.grandTotal,
                        paid_amount: formData.paid_amount,
                        balance_due: totals.grandTotal - formData.paid_amount,
                        sales_date: formData.sales_date,
                        company_name: currentCompany.name,
                        items: items.map((item: any) => ({
                            name: item.name,
                            quantity: item.quantity,
                            unit_price: item.unit_price,
                            total_amount: item.total_amount,
                        })),
                    });
                    toast.success("Email notification sent!");
                } catch {
                    toast.warning("Invoice saved, but email notification failed.");
                }
            }

            router.push("/sales");
        } catch (error: any) {
            toast.error(error.response?.data?.message || "Failed to create invoice");
        } finally {
            setLoading(false);
        }
    };

    const filteredProducts = searchQuery.length > 0
        ? products.filter(p =>
            p.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
            p.sku?.toLowerCase().includes(searchQuery.toLowerCase()) ||
            p.item_code?.toLowerCase().includes(searchQuery.toLowerCase())
        ).slice(0, 5)
        : [];

    return (
        <div className="space-y-6 max-w-[1400px] mx-auto pb-20">
            {/* Header */}
            <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                    <Button
                        variant="ghost"
                        size="icon"
                        onClick={() => router.back()}
                        className="rounded-full hover:bg-zinc-200 dark:hover:bg-zinc-800"
                    >
                        <ArrowLeft size={20} />
                    </Button>
                    <div>
                        <h2 className="text-3xl font-black tracking-tighter bg-gradient-to-r from-amber-500 via-indigo-600 to-pink-500 bg-clip-text text-transparent">
                            CREATE INVOICE
                        </h2>
                        <p className="text-sm font-medium text-zinc-500 italic">Generate a new sale record and update inventory.</p>
                    </div>
                </div>
                <div className="flex items-center gap-3">
                    <Button variant="outline" className="rounded-full border-zinc-200 dark:border-zinc-800 font-bold text-xs uppercase tracking-widest px-6 h-11">
                        Draft
                    </Button>
                    <Button
                        form="invoice-form"
                        disabled={loading}
                        className="rounded-full bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 text-white font-bold text-xs uppercase tracking-widest px-8 shadow-lg shadow-indigo-500/25 border-0 h-11"
                    >
                        {loading ? <Receipt className="animate-spin mr-2" size={18} /> : <Save className="mr-2" size={18} />}
                        Save Invoice
                    </Button>
                </div>
            </div>

            <form id="invoice-form" onSubmit={handleSubmit} className="grid grid-cols-1 xl:grid-cols-4 gap-6">
                {/* Main Form Area */}
                <div className="xl:col-span-3 space-y-6">
                    {/* Top Section: Basic Info */}
                    <Card className="border-0 bg-white dark:bg-zinc-900 shadow-2xl shadow-indigo-500/5 rounded-3xl overflow-hidden">
                        <CardContent className="p-8">
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                                <div className="space-y-3">
                                    <Label className="text-[10px] font-black uppercase tracking-widest text-zinc-400">Warehouse*</Label>
                                    <Select
                                        value={formData.warehouse_id}
                                        onValueChange={(v) => setFormData(prev => ({ ...prev, warehouse_id: v }))}
                                    >
                                        <SelectTrigger className="h-12 bg-zinc-50 dark:bg-zinc-800/50 border-zinc-100 dark:border-zinc-800 rounded-2xl focus:ring-2 focus:ring-indigo-500/20 transition-all font-bold">
                                            <SelectValue placeholder="Select Warehouse" />
                                        </SelectTrigger>
                                        <SelectContent className="rounded-2xl border-zinc-100 dark:border-zinc-800 shadow-2xl">
                                            {warehouses.map(w => (
                                                <SelectItem key={w.id} value={w.id.toString()} className="rounded-xl my-1">{w.name}</SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                </div>

                                <div className="space-y-3">
                                    <div className="flex items-center justify-between">
                                        <Label className="text-[10px] font-black uppercase tracking-widest text-zinc-400">Customer Name*</Label>
                                        {selectedCustomer && (
                                            <span className="text-[10px] font-bold text-red-500 italic">
                                                (Previous Due: ${Number(selectedCustomer.previous_due || 0).toFixed(2)})
                                            </span>
                                        )}
                                    </div>
                                    <div className="flex gap-2">
                                        <Select
                                            value={formData.customer_id}
                                            onValueChange={(v) => setFormData(prev => ({ ...prev, customer_id: v }))}
                                        >
                                            <SelectTrigger className="h-12 flex-1 bg-zinc-50 dark:bg-zinc-800/50 border-zinc-100 dark:border-zinc-800 rounded-2xl focus:ring-2 focus:ring-indigo-500/20 transition-all font-bold">
                                                <SelectValue placeholder="Select Customer" />
                                            </SelectTrigger>
                                            <SelectContent className="rounded-2xl border-zinc-100 dark:border-zinc-800 shadow-2xl">
                                                {customers.map(c => (
                                                    <SelectItem key={c.id} value={c.id.toString()} className="rounded-xl my-1">{c.name}</SelectItem>
                                                ))}
                                            </SelectContent>
                                        </Select>
                                        <Button type="button" variant="outline" size="icon" className="h-12 w-12 rounded-2xl border-zinc-100 dark:border-zinc-800 shrink-0 hover:bg-indigo-50 dark:hover:bg-indigo-900/10">
                                            <UserPlus size={18} className="text-indigo-600" />
                                        </Button>
                                    </div>
                                </div>

                                <div className="space-y-3">
                                    <Label className="text-[10px] font-black uppercase tracking-widest text-zinc-400">Sales Date*</Label>
                                    <div className="relative">
                                        <Input
                                            type="date"
                                            value={formData.sales_date}
                                            onChange={(e) => setFormData(prev => ({ ...prev, sales_date: e.target.value }))}
                                            className="h-12 pl-12 bg-zinc-50 dark:bg-zinc-800/50 border-zinc-100 dark:border-zinc-800 rounded-2xl focus:ring-2 focus:ring-indigo-500/20 transition-all font-bold"
                                        />
                                        <Calendar className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-400" size={18} />
                                    </div>
                                </div>
                            </div>
                        </CardContent>
                    </Card>

                    {/* Item Search & Table */}
                    <Card className="border-0 bg-white dark:bg-zinc-900 shadow-2xl shadow-indigo-500/5 rounded-3xl overflow-hidden">
                        <CardContent className="p-0">
                            <div className="p-8 pb-4">
                                <div className="relative group">
                                    <Input
                                        placeholder="Scan barcode or search items by name, code..."
                                        value={searchQuery}
                                        onChange={(e) => setSearchQuery(e.target.value)}
                                        className="h-14 pl-14 pr-14 bg-zinc-50 dark:bg-zinc-800/50 border-zinc-100 dark:border-zinc-800 rounded-2xl focus:ring-4 focus:ring-indigo-500/10 transition-all font-medium text-lg placeholder:text-zinc-400 italic"
                                    />
                                    <Search className="absolute left-6 top-1/2 -translate-y-1/2 text-zinc-400 group-focus-within:text-indigo-500 transition-colors" size={22} />
                                    <QrCode className="absolute right-6 top-1/2 -translate-y-1/2 text-zinc-400 cursor-pointer hover:text-indigo-500 transition-colors" size={22} />

                                    {/* Search Results Dropdown */}
                                    {filteredProducts.length > 0 && (
                                        <div className="absolute top-full left-0 right-0 mt-3 bg-white dark:bg-zinc-900 border border-zinc-100 dark:border-zinc-800 rounded-3xl shadow-[0_32px_64px_-12px_rgba(0,0,0,0.14)] z-50 p-2 overflow-hidden backdrop-blur-xl bg-opacity-95">
                                            {filteredProducts.map(p => (
                                                <div
                                                    key={p.id}
                                                    onClick={() => addItem(p)}
                                                    className="flex items-center justify-between p-4 cursor-pointer hover:bg-indigo-50 dark:hover:bg-indigo-900/20 rounded-2xl transition-all group"
                                                >
                                                    <div className="flex items-center gap-4">
                                                        <div className="h-10 w-10 rounded-xl bg-zinc-100 dark:bg-zinc-800 flex items-center justify-center font-bold text-xs text-zinc-400 group-hover:bg-indigo-600 group-hover:text-white transition-colors">
                                                            {p.name[0]}
                                                        </div>
                                                        <div>
                                                            <div className="font-bold text-zinc-900 dark:text-zinc-100">{p.name}</div>
                                                            <div className="text-[10px] text-zinc-500 font-medium tracking-wider uppercase">{p.item_code} | SKU: {p.sku || 'N/A'}</div>
                                                        </div>
                                                    </div>
                                                    <div className="text-right">
                                                        <div className="font-black text-indigo-600">${p.sales_price}</div>
                                                        <div className={cn(
                                                            "text-[10px] font-bold uppercase tracking-widest",
                                                            p.stock_quantity <= 0 ? "text-red-500" : "text-zinc-400"
                                                        )}>
                                                            {p.stock_quantity <= 0 ? "Out of Stock" : `Stock: ${p.stock_quantity}`}
                                                        </div>
                                                    </div>
                                                </div>
                                            ))}
                                        </div>
                                    )}
                                </div>
                            </div>

                            <div className="overflow-x-auto min-h-[300px]">
                                <Table>
                                    <TableHeader>
                                        <TableRow className="border-zinc-50 dark:border-zinc-800 hover:bg-transparent">
                                            <TableHead className="pl-8 text-[10px] font-black uppercase tracking-widest text-zinc-400 h-14">Item Name</TableHead>
                                            <TableHead className="text-[10px] font-black uppercase tracking-widest text-zinc-400 h-14 text-center">Qty</TableHead>
                                            <TableHead className="text-[10px] font-black uppercase tracking-widest text-zinc-400 h-14 text-right">Unit Price</TableHead>
                                            <TableHead className="text-[10px] font-black uppercase tracking-widest text-zinc-400 h-14 text-right">Discount</TableHead>
                                            <TableHead className="text-[10px] font-black uppercase tracking-widest text-zinc-400 h-14 text-right">Tax</TableHead>
                                            <TableHead className="pr-8 text-[10px] font-black uppercase tracking-widest text-zinc-400 h-14 text-right">Total Amount</TableHead>
                                            <TableHead className="w-16"></TableHead>
                                        </TableRow>
                                    </TableHeader>
                                    <TableBody>
                                        {items.map((item, idx) => (
                                            <TableRow key={idx} className="border-zinc-50 dark:border-zinc-800 hover:bg-zinc-50/50 dark:hover:bg-zinc-800/30 transition-colors group">
                                                <TableCell className="pl-8 py-6">
                                                    <div className="font-bold text-zinc-900 dark:text-zinc-100">{item.name}</div>
                                                </TableCell>
                                                <TableCell className="text-center">
                                                    <Input
                                                        type="number"
                                                        value={item.quantity}
                                                        onChange={(e) => updateItem(idx, 'quantity', Number(e.target.value))}
                                                        className="h-10 w-20 mx-auto bg-transparent border-zinc-100 dark:border-zinc-800 rounded-xl text-center font-bold"
                                                    />
                                                </TableCell>
                                                <TableCell className="text-right">
                                                    <Input
                                                        type="number"
                                                        value={item.unit_price}
                                                        onChange={(e) => updateItem(idx, 'unit_price', Number(e.target.value))}
                                                        className="h-10 w-28 ml-auto bg-transparent border-zinc-100 dark:border-zinc-800 rounded-xl text-right font-bold"
                                                    />
                                                </TableCell>
                                                <TableCell className="text-right">
                                                    <div className="font-bold text-zinc-400">${item.discount_amount}</div>
                                                </TableCell>
                                                <TableCell className="text-right">
                                                    <div className="font-bold text-zinc-400">${item.tax_amount}</div>
                                                </TableCell>
                                                <TableCell className="pr-8 text-right">
                                                    <div className="font-black text-indigo-600">${Number(item.total_amount).toFixed(2)}</div>
                                                </TableCell>
                                                <TableCell className="pr-8">
                                                    <Button
                                                        type="button"
                                                        variant="ghost"
                                                        size="icon"
                                                        onClick={() => removeItem(idx)}
                                                        className="h-10 w-10 rounded-xl text-zinc-300 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-900/10 opacity-0 group-hover:opacity-100 transition-all"
                                                    >
                                                        <Trash2 size={16} />
                                                    </Button>
                                                </TableCell>
                                            </TableRow>
                                        ))}
                                        {items.length === 0 && (
                                            <TableRow>
                                                <TableCell colSpan={7} className="h-40 text-center">
                                                    <div className="flex flex-col items-center gap-3 text-zinc-400 italic">
                                                        <ShoppingCart size={32} className="opacity-20" />
                                                        <span>Add items to your invoice to get started.</span>
                                                    </div>
                                                </TableCell>
                                            </TableRow>
                                        )}
                                    </TableBody>
                                </Table>
                            </div>
                        </CardContent>
                    </Card>

                    {/* Previous Payments Information */}
                    <div className="space-y-3">
                        <Label className="text-sm font-black text-zinc-500 uppercase tracking-widest pl-2">Previous Payments Information :</Label>
                        <Card className="border-0 bg-white dark:bg-zinc-900 shadow-xl shadow-black/5 rounded-2xl overflow-hidden">
                            <Table>
                                <TableHeader className="bg-zinc-100 dark:bg-zinc-800/50">
                                    <TableRow className="hover:bg-transparent border-0">
                                        <TableHead className="text-[10px] font-black uppercase tracking-widest text-zinc-500 w-12 text-center">#</TableHead>
                                        <TableHead className="text-[10px] font-black uppercase tracking-widest text-zinc-500">Date</TableHead>
                                        <TableHead className="text-[10px] font-black uppercase tracking-widest text-zinc-500">Payment Type</TableHead>
                                        <TableHead className="text-[10px] font-black uppercase tracking-widest text-zinc-500">Payment Note</TableHead>
                                        <TableHead className="text-[10px] font-black uppercase tracking-widest text-zinc-500 text-right">Payment</TableHead>
                                        <TableHead className="text-[10px] font-black uppercase tracking-widest text-zinc-500 text-center">Action</TableHead>
                                    </TableRow>
                                </TableHeader>
                                <TableBody>
                                    {previousPayments.length > 0 ? (
                                        previousPayments.map((p, idx) => (
                                            <TableRow key={p.id}>
                                                <TableCell className="text-center font-bold text-zinc-400">{idx + 1}</TableCell>
                                                <TableCell className="font-medium text-zinc-600">{p.date}</TableCell>
                                                <TableCell className="font-medium text-zinc-600">{p.payment_type}</TableCell>
                                                <TableCell className="text-zinc-400">{p.note}</TableCell>
                                                <TableCell className="text-right font-black text-indigo-600">${Number(p.amount).toFixed(2)}</TableCell>
                                                <TableCell className="text-center">
                                                    <Button variant="ghost" size="icon" className="h-8 w-8 text-red-500">
                                                        <Trash2 size={14} />
                                                    </Button>
                                                </TableCell>
                                            </TableRow>
                                        ))
                                    ) : (
                                        <TableRow className="hover:bg-transparent border-0">
                                            <TableCell colSpan={6} className="h-16 text-center text-sm font-bold text-zinc-400 italic">
                                                Payments Pending!!
                                            </TableCell>
                                        </TableRow>
                                    )}
                                </TableBody>
                            </Table>
                        </Card>
                    </div>

                    {/* Terms and Conditions */}
                    <div className="space-y-4">
                        <div className="flex items-center justify-between">
                            <Label className="text-sm font-bold text-zinc-700 dark:text-zinc-300">Invoice Terms and Conditions</Label>
                            <div className="h-px flex-1 bg-red-500/20 mx-4" />
                            <Minus size={16} className="text-red-500 cursor-pointer" />
                        </div>
                        <textarea
                            className="w-full min-h-[140px] bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-xl p-6 font-mono text-sm text-zinc-600 dark:text-zinc-400 focus:ring-4 focus:ring-indigo-500/5 focus:border-indigo-500/20 transition-all outline-none resize-none shadow-inner"
                            placeholder="Type your terms and conditions here..."
                            value={formData.terms_and_conditions}
                            onChange={(e) => setFormData(prev => ({ ...prev, terms_and_conditions: e.target.value }))}
                        />
                    </div>

                    {/* Payment Section */}
                    <div className="space-y-4">
                        <div className="space-y-4">
                            <Label className="text-[10px] font-black uppercase tracking-widest text-zinc-400">Payment Status</Label>
                            <div className="flex gap-4">
                                <Button
                                    type="button"
                                    onClick={() => setFormData(prev => ({ ...prev, paid_amount: totals.grandTotal }))}
                                    className={cn(
                                        "flex-1 h-14 rounded-full font-black uppercase tracking-widest transition-all border-zinc-200 dark:border-zinc-800",
                                        totals.paymentStatus === 'PAID'
                                            ? "bg-emerald-500 text-white shadow-lg shadow-emerald-500/25 border-0"
                                            : "bg-white dark:bg-zinc-900 border text-zinc-400"
                                    )}
                                >
                                    PAID
                                </Button>
                                <Button
                                    type="button"
                                    onClick={() => {
                                        // Focus the paid amount field if partial is clicked
                                        document.getElementById('paid-amount-input')?.focus();
                                    }}
                                    className={cn(
                                        "flex-1 h-14 rounded-full font-black uppercase tracking-widest transition-all border-zinc-200 dark:border-zinc-800",
                                        totals.paymentStatus === 'PARTIAL'
                                            ? "bg-orange-500 text-white shadow-lg shadow-orange-500/25 border-0"
                                            : "bg-white dark:bg-zinc-900 border text-zinc-400"
                                    )}
                                >
                                    PARTIAL
                                </Button>
                                <Button
                                    type="button"
                                    onClick={() => setFormData(prev => ({ ...prev, paid_amount: 0 }))}
                                    className={cn(
                                        "flex-1 h-14 rounded-full font-black uppercase tracking-widest transition-all border-zinc-200 dark:border-zinc-800",
                                        totals.paymentStatus === 'UNPAID'
                                            ? "bg-zinc-800 text-white shadow-lg shadow-black/25 border-0"
                                            : "bg-white dark:bg-zinc-900 border text-zinc-400"
                                    )}
                                >
                                    UNPAID
                                </Button>
                            </div>
                        </div>

                        <Label className="text-lg font-black text-indigo-600 pt-4 block">Payment :</Label>
                        <div className="text-xs font-bold text-zinc-500 mb-2">Advance : 0.00</div>

                        <div className="flex items-center gap-2 mb-4">
                            <input type="checkbox" id="adjust-advance" className="h-4 w-4 rounded border-zinc-300 text-indigo-600 focus:ring-indigo-500" />
                            <label htmlFor="adjust-advance" className="text-xs font-bold text-zinc-600">Adjust Advance Payment</label>
                        </div>

                        <div className="bg-zinc-100 dark:bg-zinc-800/40 rounded-2xl p-8 grid grid-cols-1 md:grid-cols-3 gap-8 border border-zinc-200/50 dark:border-zinc-800">
                            <div className="space-y-3">
                                <Label className="text-[10px] font-black uppercase tracking-widest text-zinc-400">Amount</Label>
                                <div className="relative">
                                    <Input
                                        id="paid-amount-input"
                                        type="number"
                                        value={formData.paid_amount}
                                        onChange={(e) => setFormData(prev => ({ ...prev, paid_amount: Number(e.target.value) }))}
                                        className="h-12 text-right font-black text-xl bg-white dark:bg-zinc-900 border-zinc-200 dark:border-zinc-800 rounded-xl focus:ring-indigo-500/20"
                                    />
                                    <div className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-400 font-bold">$</div>
                                </div>
                            </div>

                            <div className="space-y-3">
                                <Label className="text-[10px] font-black uppercase tracking-widest text-zinc-400">Payment Type</Label>
                                <Select
                                    value={formData.payment_type}
                                    onValueChange={(v) => setFormData(prev => ({ ...prev, payment_type: v }))}
                                >
                                    <SelectTrigger className="h-12 bg-white dark:bg-zinc-900 border-zinc-200 dark:border-zinc-800 rounded-xl font-bold">
                                        <SelectValue placeholder="-Select-" />
                                    </SelectTrigger>
                                    <SelectContent className="rounded-xl border-zinc-200 dark:border-zinc-800">
                                        <SelectItem value="Cash">Cash</SelectItem>
                                        <SelectItem value="Card">Card</SelectItem>
                                        <SelectItem value="Bank Transfer">Bank Transfer</SelectItem>
                                        <SelectItem value="Cheque">Cheque</SelectItem>
                                    </SelectContent>
                                </Select>
                            </div>

                            <div className="space-y-3">
                                <Label className="text-[10px] font-black uppercase tracking-widest text-zinc-400">Account</Label>
                                <Select
                                    value={formData.account_id}
                                    onValueChange={(v) => setFormData(prev => ({ ...prev, account_id: v }))}
                                >
                                    <SelectTrigger className="h-12 bg-white dark:bg-zinc-900 border-zinc-200 dark:border-zinc-800 rounded-xl font-bold">
                                        <SelectValue placeholder="Select Account" />
                                    </SelectTrigger>
                                    <SelectContent className="rounded-xl border-zinc-200 dark:border-zinc-800">
                                        {accounts.map(acc => (
                                            <SelectItem key={acc.id} value={acc.id.toString()} className="rounded-lg">{acc.name}</SelectItem>
                                        ))}
                                    </SelectContent>
                                </Select>
                            </div>

                            <div className="md:col-span-3 space-y-3">
                                <Label className="text-[10px] font-black uppercase tracking-widest text-zinc-400">Payment Note</Label>
                                <textarea
                                    className="w-full min-h-[80px] bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-xl p-4 font-medium focus:ring-4 focus:ring-indigo-500/5 focus:border-indigo-500/20 transition-all outline-none resize-none"
                                    placeholder="Write any payment related notes..."
                                    value={formData.payment_note}
                                    onChange={(e) => setFormData(prev => ({ ...prev, payment_note: e.target.value }))}
                                />
                            </div>
                        </div>
                    </div>

                    <div className="space-y-3 py-4 border-t border-zinc-100 dark:border-zinc-800/30">
                        {/* WhatsApp Notification Row */}
                        <div className="flex items-center gap-4 flex-wrap">
                            <div className="flex items-center gap-3">
                                <input type="checkbox" id="send-msg" checked={sendWhatsapp} onChange={(e) => setSendWhatsapp(e.target.checked)} className="h-5 w-5 rounded border-green-500 cursor-pointer accent-green-500" />
                                <label htmlFor="send-msg" className="text-sm font-bold text-zinc-600 dark:text-zinc-300 flex items-center gap-2 cursor-pointer">
                                    <MessageCircle size={16} className="text-green-500" /> WhatsApp Notification
                                </label>
                            </div>
                            {sendWhatsapp && !whatsappConfig && (<span className="text-[10px] font-bold text-amber-500 italic">(No active gateway)</span>)}
                            {sendWhatsapp && whatsappConfig && !selectedCustomer?.mobile && (<span className="text-[10px] font-bold text-amber-500 italic">(No mobile number)</span>)}
                            {sendWhatsapp && whatsappConfig && selectedCustomer?.mobile && (<span className="text-[10px] font-bold text-green-600 italic">→ {selectedCustomer.mobile}</span>)}
                        </div>
                        {/* Email Notification Row */}
                        <div className="flex items-center gap-4 flex-wrap">
                            <div className="flex items-center gap-3">
                                <input type="checkbox" id="send-email" checked={sendEmail} onChange={(e) => setSendEmail(e.target.checked)} className="h-5 w-5 rounded border-indigo-500 cursor-pointer accent-indigo-500" />
                                <label htmlFor="send-email" className="text-sm font-bold text-zinc-600 dark:text-zinc-300 flex items-center gap-2 cursor-pointer">
                                    <Mail size={16} className="text-indigo-500" /> Email Notification
                                </label>
                            </div>
                            {sendEmail && !emailConfig && (<span className="text-[10px] font-bold text-amber-500 italic">(No active email config)</span>)}
                            {sendEmail && emailConfig && !selectedCustomer?.email && (<span className="text-[10px] font-bold text-amber-500 italic">(No email address)</span>)}
                            {sendEmail && emailConfig && selectedCustomer?.email && (<span className="text-[10px] font-bold text-indigo-600 italic">→ {selectedCustomer.email}</span>)}
                        </div>
                    </div>

                    <div className="flex items-center gap-4 pt-4">
                        <Button
                            type="submit"
                            disabled={loading}
                            className="flex-1 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-black uppercase tracking-widest h-14 shadow-xl shadow-emerald-500/20 border-0"
                        >
                            {loading ? <Receipt className="animate-spin mr-2" /> : <Save className="mr-2" />}
                            Save
                        </Button>
                        <Button
                            type="button"
                            onClick={() => router.back()}
                            className="flex-1 rounded-xl bg-orange-500 hover:bg-orange-600 text-white font-black uppercase tracking-widest h-14 shadow-xl shadow-orange-500/20 border-0"
                        >
                            Close
                        </Button>
                    </div>
                </div>

                {/* Sidebar Sticky Area */}
                <div className="space-y-6">
                    <Card className="border-0 bg-indigo-600 dark:bg-indigo-700 shadow-2xl shadow-indigo-500/20 rounded-[32px] overflow-hidden sticky top-24">
                        <CardContent className="p-8 space-y-8 text-white">
                            <div className="space-y-2">
                                <p className="text-[10px] font-black uppercase tracking-widest text-white/60 italic">Grand Total</p>
                                <h3 className={cn(
                                    "font-black tracking-tighter transition-all duration-300",
                                    getDynamicFontSize(`$ ${Number(totals.grandTotal).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 'grandTotal')
                                )}>$ {Number(totals.grandTotal).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</h3>
                            </div>

                            <div className="space-y-6 pt-6 border-t border-white/10">
                                <div className="space-y-3">
                                    <Label className="text-[10px] font-black uppercase tracking-widest text-white/60">Discount on All</Label>
                                    <div className="flex gap-2">
                                        <Input
                                            type="number"
                                            value={formData.discount_on_all}
                                            onChange={(e) => setFormData(prev => ({ ...prev, discount_on_all: Number(e.target.value) }))}
                                            className="h-11 bg-white/10 border-white/10 rounded-xl focus:ring-white/20 text-white font-bold"
                                        />
                                        <Select
                                            value={formData.discount_type}
                                            onValueChange={(v: any) => setFormData(prev => ({ ...prev, discount_type: v }))}
                                        >
                                            <SelectTrigger className="h-11 w-24 bg-white/10 border-white/10 rounded-xl text-white font-bold">
                                                <SelectValue />
                                            </SelectTrigger>
                                            <SelectContent className="rounded-xl border-zinc-100 dark:border-zinc-800">
                                                <SelectItem value="Percentage" className="rounded-lg">%</SelectItem>
                                                <SelectItem value="Fixed" className="rounded-lg">$</SelectItem>
                                            </SelectContent>
                                        </Select>
                                    </div>
                                </div>

                                <div className="space-y-3">
                                    <Label className="text-[10px] font-black uppercase tracking-widest text-white/60">Paid Amount</Label>
                                    <Input
                                        type="number"
                                        value={formData.paid_amount}
                                        onChange={(e) => setFormData(prev => ({ ...prev, paid_amount: Number(e.target.value) }))}
                                        className={cn(
                                            "h-14 bg-white/20 border-white/20 rounded-2xl focus:ring-white/40 text-white font-black transition-all duration-300 px-4",
                                            getDynamicFontSize(formData.paid_amount.toString(), 'paidAmount')
                                        )}
                                    />
                                </div>

                                <div className="p-6 rounded-3xl bg-black/10 backdrop-blur-md space-y-4">
                                    <div className="flex justify-between items-center">
                                        <span className="text-[10px] font-bold uppercase tracking-widest text-white/40 italic">Balance Due</span>
                                        <span className={cn(
                                            "font-black px-4 py-1 rounded-full transition-all duration-300 whitespace-nowrap",
                                            getDynamicFontSize(`$ ${Number(totals.balance).toFixed(2)}`, 'balanceDue'),
                                            totals.balance > 0 ? "bg-red-500/20 text-red-200" : "bg-emerald-500/20 text-emerald-200"
                                        )}>
                                            $ {Number(totals.balance).toFixed(2)}
                                        </span>
                                    </div>
                                    <div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-white/30 italic">
                                        <Receipt size={14} className="opacity-50" />
                                        Invoicing for {currentCompany?.name}
                                    </div>
                                </div>
                            </div>
                        </CardContent>
                    </Card>

                </div>
            </form>
        </div>
    );
}
